[project]
name = "ioi-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "model-library>=0.1.3",
    "pypdf2>=3.0.1",
    "python-dotenv>=1.2.1",
]
